// archivo: colombia_cities.dart
const List<Map<String, String>> colombiaCities = [
  {'name': 'Medellín, Antioquia', 'dane': '05001'},
  {'name': 'Abejorral, Antioquia', 'dane': '05002'},
  {'name': 'Abriaquí, Antioquia', 'dane': '05004'},
  {'name': 'Alejandría, Antioquia', 'dane': '05021'},
  {'name': 'Amagá, Antioquia', 'dane': '05030'},
  {'name': 'Amalfi, Antioquia', 'dane': '05031'},
  {'name': 'Andes, Antioquia', 'dane': '05034'},
  {'name': 'Angelópolis, Antioquia', 'dane': '05036'},
  {'name': 'Angostura, Antioquia', 'dane': '05038'},
  {'name': 'Anorí, Antioquia', 'dane': '05040'},
  {'name': 'Santa Fé De Antioquia, Antioquia', 'dane': '05042'},
  {'name': 'Anzá, Antioquia', 'dane': '05044'},
  {'name': 'Apartadó, Antioquia', 'dane': '05045'},
  {'name': 'Arboletes, Antioquia', 'dane': '05051'},
  {'name': 'Argelia, Antioquia', 'dane': '05055'},
  {'name': 'Armenia, Antioquia', 'dane': '05059'},
  {'name': 'Barbosa, Antioquia', 'dane': '05079'},
  {'name': 'Belmira, Antioquia', 'dane': '05086'},
  {'name': 'Bello, Antioquia', 'dane': '05088'},
  {'name': 'Betania, Antioquia', 'dane': '05091'},
  {'name': 'Betulia, Antioquia', 'dane': '05093'},
  {'name': 'Ciudad Bolívar, Antioquia', 'dane': '05101'},
  {'name': 'Briceño, Antioquia', 'dane': '05107'},
  {'name': 'Buriticá, Antioquia', 'dane': '05113'},
  {'name': 'Cáceres, Antioquia', 'dane': '05120'},
  {'name': 'Caicedo, Antioquia', 'dane': '05125'},
  {'name': 'Caldas, Antioquia', 'dane': '05129'},
  {'name': 'Campamento, Antioquia', 'dane': '05134'},
  {'name': 'Cañasgordas, Antioquia', 'dane': '05138'},
  {'name': 'Caracolí, Antioquia', 'dane': '05142'},
  {'name': 'Caramanta, Antioquia', 'dane': '05145'},
  {'name': 'Carepa, Antioquia', 'dane': '05147'},
  {'name': 'El Carmen De Viboral, Antioquia', 'dane': '05148'},
  {'name': 'Carolina, Antioquia', 'dane': '05150'},
  {'name': 'Caucasia, Antioquia', 'dane': '05154'},
  {'name': 'Chigorodó, Antioquia', 'dane': '05172'},
  {'name': 'Cisneros, Antioquia', 'dane': '05190'},
  {'name': 'Cocorná, Antioquia', 'dane': '05197'},
  {'name': 'Concepción, Antioquia', 'dane': '05206'},
  {'name': 'Concordia, Antioquia', 'dane': '05209'},
  {'name': 'Copacabana, Antioquia', 'dane': '05212'},
  {'name': 'Dabeiba, Antioquia', 'dane': '05234'},
  {'name': 'Donmatías, Antioquia', 'dane': '05237'},
  {'name': 'Ebéjico, Antioquia', 'dane': '05240'},
  {'name': 'El Bagre, Antioquia', 'dane': '05250'},
  {'name': 'Entrerríos, Antioquia', 'dane': '05264'},
  {'name': 'Envigado, Antioquia', 'dane': '05266'},
  {'name': 'Fredonia, Antioquia', 'dane': '05282'},
  {'name': 'Frontino, Antioquia', 'dane': '05284'},
  {'name': 'Giraldo, Antioquia', 'dane': '05306'},
  {'name': 'Girardota, Antioquia', 'dane': '05308'},
  {'name': 'Gómez Plata, Antioquia', 'dane': '05310'},
  {'name': 'Granada, Antioquia', 'dane': '05313'},
  {'name': 'Guadalupe, Antioquia', 'dane': '05315'},
  {'name': 'Guarne, Antioquia', 'dane': '05318'},
  {'name': 'Guatapé, Antioquia', 'dane': '05321'},
  {'name': 'Heliconia, Antioquia', 'dane': '05347'},
  {'name': 'Hispania, Antioquia', 'dane': '05353'},
  {'name': 'Itagüí, Antioquia', 'dane': '05360'},
  {'name': 'Ituango, Antioquia', 'dane': '05361'},
  {'name': 'Jardín, Antioquia', 'dane': '05364'},
  {'name': 'Jericó, Antioquia', 'dane': '05368'},
  {'name': 'La Ceja, Antioquia', 'dane': '05376'},
  {'name': 'La Estrella, Antioquia', 'dane': '05380'},
  {'name': 'La Pintada, Antioquia', 'dane': '05390'},
  {'name': 'La Unión, Antioquia', 'dane': '05400'},
  {'name': 'Liborina, Antioquia', 'dane': '05411'},
  {'name': 'Maceo, Antioquia', 'dane': '05425'},
  {'name': 'Marinilla, Antioquia', 'dane': '05440'},
  {'name': 'Montebello, Antioquia', 'dane': '05467'},
  {'name': 'Murindó, Antioquia', 'dane': '05475'},
  {'name': 'Mutatá, Antioquia', 'dane': '05480'},
  {'name': 'Nariño, Antioquia', 'dane': '05483'},
  {'name': 'Necoclí, Antioquia', 'dane': '05490'},
  {'name': 'Nechí, Antioquia', 'dane': '05495'},
  {'name': 'Olaya, Antioquia', 'dane': '05501'},
  {'name': 'Peñol, Antioquia', 'dane': '05541'},
  {'name': 'Peque, Antioquia', 'dane': '05543'},
  {'name': 'Pueblorrico, Antioquia', 'dane': '05576'},
  {'name': 'Puerto Berrío, Antioquia', 'dane': '05579'},
  {'name': 'Puerto Nare, Antioquia', 'dane': '05585'},
  {'name': 'Puerto Triunfo, Antioquia', 'dane': '05591'},
  {'name': 'Remedios, Antioquia', 'dane': '05604'},
  {'name': 'Retiro, Antioquia', 'dane': '05607'},
  {'name': 'Rionegro, Antioquia', 'dane': '05615'},
  {'name': 'Sabanalarga, Antioquia', 'dane': '05628'},
  {'name': 'Sabaneta, Antioquia', 'dane': '05631'},
  {'name': 'Salgar, Antioquia', 'dane': '05642'},
  {'name': 'San Andrés De Cuerquía, Antioquia', 'dane': '05647'},
  {'name': 'San Carlos, Antioquia', 'dane': '05649'},
  {'name': 'San Francisco, Antioquia', 'dane': '05652'},
  {'name': 'San Jerónimo, Antioquia', 'dane': '05656'},
  {'name': 'San José De La Montaña, Antioquia', 'dane': '05658'},
  {'name': 'San Juan De Urabá, Antioquia', 'dane': '05659'},
  {'name': 'San Luis, Antioquia', 'dane': '05660'},
  {'name': 'San Pedro De Los Milagros, Antioquia', 'dane': '05664'},
  {'name': 'San Pedro De Urabá, Antioquia', 'dane': '05665'},
  {'name': 'San Rafael, Antioquia', 'dane': '05667'},
  {'name': 'San Roque, Antioquia', 'dane': '05670'},
  {'name': 'San Vicente Ferrer, Antioquia', 'dane': '05674'},
  {'name': 'Santa Bárbara, Antioquia', 'dane': '05679'},
  {'name': 'Santa Rosa De Osos, Antioquia', 'dane': '05686'},
  {'name': 'Santo Domingo, Antioquia', 'dane': '05690'},
  {'name': 'El Santuario, Antioquia', 'dane': '05697'},
  {'name': 'Segovia, Antioquia', 'dane': '05736'},
  {'name': 'Sonsón, Antioquia', 'dane': '05756'},
  {'name': 'Sopetrán, Antioquia', 'dane': '05761'},
  {'name': 'Támesis, Antioquia', 'dane': '05789'},
  {'name': 'Tarazá, Antioquia', 'dane': '05790'},
  {'name': 'Tarso, Antioquia', 'dane': '05792'},
  {'name': 'Titiribí, Antioquia', 'dane': '05809'},
  {'name': 'Toledo, Antioquia', 'dane': '05819'},
  {'name': 'Turbo, Antioquia', 'dane': '05837'},
  {'name': 'Uramita, Antioquia', 'dane': '05842'},
  {'name': 'Urrao, Antioquia', 'dane': '05847'},
  {'name': 'Valdivia, Antioquia', 'dane': '05854'},
  {'name': 'Valparaíso, Antioquia', 'dane': '05856'},
  {'name': 'Vegachí, Antioquia', 'dane': '05858'},
  {'name': 'Venecia, Antioquia', 'dane': '05861'},
  {'name': 'Vigía Del Fuerte, Antioquia', 'dane': '05873'},
  {'name': 'Yalí, Antioquia', 'dane': '05885'},
  {'name': 'Yarumal, Antioquia', 'dane': '05887'},
  {'name': 'Yolombó, Antioquia', 'dane': '05890'},
  {'name': 'Yondó, Antioquia', 'dane': '05893'},
  {'name': 'Zaragoza, Antioquia', 'dane': '05895'},
  {'name': 'Barranquilla, Atlántico', 'dane': '08001'},
  {'name': 'Baranoa, Atlántico', 'dane': '08078'},
  {'name': 'Campo De La Cruz, Atlántico', 'dane': '08137'},
  {'name': 'Candelaria, Atlántico', 'dane': '08141'},
  {'name': 'Galapa, Atlántico', 'dane': '08296'},
  {'name': 'Juan De Acosta, Atlántico', 'dane': '08372'},
  {'name': 'Luruaco, Atlántico', 'dane': '08421'},
  {'name': 'Malambo, Atlántico', 'dane': '08433'},
  {'name': 'Manatí, Atlántico', 'dane': '08436'},
  {'name': 'Palmar De Varela, Atlántico', 'dane': '08520'},
  {'name': 'Piojó, Atlántico', 'dane': '08549'},
  {'name': 'Polonuevo, Atlántico', 'dane': '08558'},
  {'name': 'Ponedera, Atlántico', 'dane': '08560'},
  {'name': 'Puerto Colombia, Atlántico', 'dane': '08573'},
  {'name': 'Repelón, Atlántico', 'dane': '08606'},
  {'name': 'Sabanagrande, Atlántico', 'dane': '08634'},
  {'name': 'Sabanalarga, Atlántico', 'dane': '08638'},
  {'name': 'Santa Lucía, Atlántico', 'dane': '08675'},
  {'name': 'Santo Tomás, Atlántico', 'dane': '08685'},
  {'name': 'Soledad, Atlántico', 'dane': '08758'},
  {'name': 'Suan, Atlántico', 'dane': '08770'},
  {'name': 'Tubará, Atlántico', 'dane': '08832'},
  {'name': 'Usiacurí, Atlántico', 'dane': '08849'},
  {'name': 'Bogotá, D.c., Bogotá, D.c.', 'dane': '11001'},
  {'name': 'Cartagena De Indias, Bolívar', 'dane': '13001'},
  {'name': 'Achí, Bolívar', 'dane': '13006'},
  {'name': 'Altos Del Rosario, Bolívar', 'dane': '13030'},
  {'name': 'Arenal, Bolívar', 'dane': '13042'},
  {'name': 'Arjona, Bolívar', 'dane': '13052'},
  {'name': 'Arroyohondo, Bolívar', 'dane': '13062'},
  {'name': 'Barranco De Loba, Bolívar', 'dane': '13074'},
  {'name': 'Calamar, Bolívar', 'dane': '13140'},
  {'name': 'Cantagallo, Bolívar', 'dane': '13160'},
  {'name': 'Cicuco, Bolívar', 'dane': '13188'},
  {'name': 'Córdoba, Bolívar', 'dane': '13212'},
  {'name': 'Clemencia, Bolívar', 'dane': '13222'},
  {'name': 'El Carmen De Bolívar, Bolívar', 'dane': '13244'},
  {'name': 'El Guamo, Bolívar', 'dane': '13248'},
  {'name': 'El Peñón, Bolívar', 'dane': '13268'},
  {'name': 'Hatillo De Loba, Bolívar', 'dane': '13300'},
  {'name': 'Magangué, Bolívar', 'dane': '13430'},
  {'name': 'Mahates, Bolívar', 'dane': '13433'},
  {'name': 'Margarita, Bolívar', 'dane': '13440'},
  {'name': 'María La Baja, Bolívar', 'dane': '13442'},
  {'name': 'Montecristo, Bolívar', 'dane': '13458'},
  {'name': 'Santa Cruz De Mompox, Bolívar', 'dane': '13468'},
  {'name': 'Morales, Bolívar', 'dane': '13473'},
  {'name': 'Norosí, Bolívar', 'dane': '13490'},
  {'name': 'Pinillos, Bolívar', 'dane': '13549'},
  {'name': 'Regidor, Bolívar', 'dane': '13580'},
  {'name': 'Río Viejo, Bolívar', 'dane': '13600'},
  {'name': 'San Cristóbal, Bolívar', 'dane': '13620'},
  {'name': 'San Estanislao, Bolívar', 'dane': '13647'},
  {'name': 'San Fernando, Bolívar', 'dane': '13650'},
  {'name': 'San Jacinto, Bolívar', 'dane': '13654'},
  {'name': 'San Jacinto Del Cauca, Bolívar', 'dane': '13655'},
  {'name': 'San Juan Nepomuceno, Bolívar', 'dane': '13657'},
  {'name': 'San Martín De Loba, Bolívar', 'dane': '13667'},
  {'name': 'San Pablo, Bolívar', 'dane': '13670'},
  {'name': 'Santa Catalina, Bolívar', 'dane': '13673'},
  {'name': 'Santa Rosa, Bolívar', 'dane': '13683'},
  {'name': 'Santa Rosa Del Sur, Bolívar', 'dane': '13688'},
  {'name': 'Simití, Bolívar', 'dane': '13744'},
  {'name': 'Soplaviento, Bolívar', 'dane': '13760'},
  {'name': 'Talaigua Nuevo, Bolívar', 'dane': '13780'},
  {'name': 'Tiquisio, Bolívar', 'dane': '13810'},
  {'name': 'Turbaco, Bolívar', 'dane': '13836'},
  {'name': 'Turbaná, Bolívar', 'dane': '13838'},
  {'name': 'Villanueva, Bolívar', 'dane': '13873'},
  {'name': 'Zambrano, Bolívar', 'dane': '13894'},
  {'name': 'Tunja, Boyacá', 'dane': '15001'},
  {'name': 'Almeida, Boyacá', 'dane': '15022'},
  {'name': 'Aquitania, Boyacá', 'dane': '15047'},
  {'name': 'Arcabuco, Boyacá', 'dane': '15051'},
  {'name': 'Belén, Boyacá', 'dane': '15087'},
  {'name': 'Berbeo, Boyacá', 'dane': '15090'},
  {'name': 'Betéitiva, Boyacá', 'dane': '15092'},
  {'name': 'Boavita, Boyacá', 'dane': '15097'},
  {'name': 'Boyacá, Boyacá', 'dane': '15104'},
  {'name': 'Briceño, Boyacá', 'dane': '15106'},
  {'name': 'Buenavista, Boyacá', 'dane': '15109'},
  {'name': 'Busbanzá, Boyacá', 'dane': '15114'},
  {'name': 'Caldas, Boyacá', 'dane': '15131'},
  {'name': 'Campohermoso, Boyacá', 'dane': '15135'},
  {'name': 'Cerinza, Boyacá', 'dane': '15162'},
  {'name': 'Chinavita, Boyacá', 'dane': '15172'},
  {'name': 'Chiquinquirá, Boyacá', 'dane': '15176'},
  {'name': 'Chiscas, Boyacá', 'dane': '15180'},
  {'name': 'Chita, Boyacá', 'dane': '15183'},
  {'name': 'Chitaraque, Boyacá', 'dane': '15185'},
  {'name': 'Chivatá, Boyacá', 'dane': '15187'},
  {'name': 'Ciénega, Boyacá', 'dane': '15189'},
  {'name': 'Cómbita, Boyacá', 'dane': '15204'},
  {'name': 'Coper, Boyacá', 'dane': '15212'},
  {'name': 'Corrales, Boyacá', 'dane': '15215'},
  {'name': 'Covarachía, Boyacá', 'dane': '15218'},
  {'name': 'Cubará, Boyacá', 'dane': '15223'},
  {'name': 'Cucaita, Boyacá', 'dane': '15224'},
  {'name': 'Cuítiva, Boyacá', 'dane': '15226'},
  {'name': 'Chíquiza, Boyacá', 'dane': '15232'},
  {'name': 'Chivor, Boyacá', 'dane': '15236'},
  {'name': 'Duitama, Boyacá', 'dane': '15238'},
  {'name': 'El Cocuy, Boyacá', 'dane': '15244'},
  {'name': 'El Espino, Boyacá', 'dane': '15248'},
  {'name': 'Firavitoba, Boyacá', 'dane': '15272'},
  {'name': 'Floresta, Boyacá', 'dane': '15276'},
  {'name': 'Gachantivá, Boyacá', 'dane': '15293'},
  {'name': 'Gámeza, Boyacá', 'dane': '15296'},
  {'name': 'Garagoa, Boyacá', 'dane': '15299'},
  {'name': 'Guacamayas, Boyacá', 'dane': '15317'},
  {'name': 'Guateque, Boyacá', 'dane': '15322'},
  {'name': 'Guayatá, Boyacá', 'dane': '15325'},
  {'name': 'Güicán De La Sierra, Boyacá', 'dane': '15332'},
  {'name': 'Iza, Boyacá', 'dane': '15362'},
  {'name': 'Jenesano, Boyacá', 'dane': '15367'},
  {'name': 'Jericó, Boyacá', 'dane': '15368'},
  {'name': 'Labranzagrande, Boyacá', 'dane': '15377'},
  {'name': 'La Capilla, Boyacá', 'dane': '15380'},
  {'name': 'La Victoria, Boyacá', 'dane': '15401'},
  {'name': 'La Uvita, Boyacá', 'dane': '15403'},
  {'name': 'Villa De Leyva, Boyacá', 'dane': '15407'},
  {'name': 'Macanal, Boyacá', 'dane': '15425'},
  {'name': 'Maripí, Boyacá', 'dane': '15442'},
  {'name': 'Miraflores, Boyacá', 'dane': '15455'},
  {'name': 'Mongua, Boyacá', 'dane': '15464'},
  {'name': 'Monguí, Boyacá', 'dane': '15466'},
  {'name': 'Moniquirá, Boyacá', 'dane': '15469'},
  {'name': 'Motavita, Boyacá', 'dane': '15476'},
  {'name': 'Muzo, Boyacá', 'dane': '15480'},
  {'name': 'Nobsa, Boyacá', 'dane': '15491'},
  {'name': 'Nuevo Colón, Boyacá', 'dane': '15494'},
  {'name': 'Oicatá, Boyacá', 'dane': '15500'},
  {'name': 'Otanche, Boyacá', 'dane': '15507'},
  {'name': 'Pachavita, Boyacá', 'dane': '15511'},
  {'name': 'Páez, Boyacá', 'dane': '15514'},
  {'name': 'Paipa, Boyacá', 'dane': '15516'},
  {'name': 'Pajarito, Boyacá', 'dane': '15518'},
  {'name': 'Panqueba, Boyacá', 'dane': '15522'},
  {'name': 'Pauna, Boyacá', 'dane': '15531'},
  {'name': 'Paya, Boyacá', 'dane': '15533'},
  {'name': 'Paz De Río, Boyacá', 'dane': '15537'},
  {'name': 'Pesca, Boyacá', 'dane': '15542'},
  {'name': 'Pisba, Boyacá', 'dane': '15550'},
  {'name': 'Puerto Boyacá, Boyacá', 'dane': '15572'},
  {'name': 'Quípama, Boyacá', 'dane': '15580'},
  {'name': 'Ramiriquí, Boyacá', 'dane': '15599'},
  {'name': 'Ráquira, Boyacá', 'dane': '15600'},
  {'name': 'Rondón, Boyacá', 'dane': '15621'},
  {'name': 'Saboyá, Boyacá', 'dane': '15632'},
  {'name': 'Sáchica, Boyacá', 'dane': '15638'},
  {'name': 'Samacá, Boyacá', 'dane': '15646'},
  {'name': 'San Eduardo, Boyacá', 'dane': '15660'},
  {'name': 'San José De Pare, Boyacá', 'dane': '15664'},
  {'name': 'San Luis De Gaceno, Boyacá', 'dane': '15667'},
  {'name': 'San Mateo, Boyacá', 'dane': '15673'},
  {'name': 'San Miguel De Sema, Boyacá', 'dane': '15676'},
  {'name': 'San Pablo De Borbur, Boyacá', 'dane': '15681'},
  {'name': 'Santana, Boyacá', 'dane': '15686'},
  {'name': 'Santa María, Boyacá', 'dane': '15690'},
  {'name': 'Santa Rosa De Viterbo, Boyacá', 'dane': '15693'},
  {'name': 'Santa Sofía, Boyacá', 'dane': '15696'},
  {'name': 'Sativanorte, Boyacá', 'dane': '15720'},
  {'name': 'Sativasur, Boyacá', 'dane': '15723'},
  {'name': 'Siachoque, Boyacá', 'dane': '15740'},
  {'name': 'Soatá, Boyacá', 'dane': '15753'},
  {'name': 'Socotá, Boyacá', 'dane': '15755'},
  {'name': 'Socha, Boyacá', 'dane': '15757'},
  {'name': 'Sogamoso, Boyacá', 'dane': '15759'},
  {'name': 'Somondoco, Boyacá', 'dane': '15761'},
  {'name': 'Sora, Boyacá', 'dane': '15762'},
  {'name': 'Sotaquirá, Boyacá', 'dane': '15763'},
  {'name': 'Soracá, Boyacá', 'dane': '15764'},
  {'name': 'Susacón, Boyacá', 'dane': '15774'},
  {'name': 'Sutamarchán, Boyacá', 'dane': '15776'},
  {'name': 'Sutatenza, Boyacá', 'dane': '15778'},
  {'name': 'Tasco, Boyacá', 'dane': '15790'},
  {'name': 'Tenza, Boyacá', 'dane': '15798'},
  {'name': 'Tibaná, Boyacá', 'dane': '15804'},
  {'name': 'Tibasosa, Boyacá', 'dane': '15806'},
  {'name': 'Tinjacá, Boyacá', 'dane': '15808'},
  {'name': 'Tipacoque, Boyacá', 'dane': '15810'},
  {'name': 'Toca, Boyacá', 'dane': '15814'},
  {'name': 'Togüí, Boyacá', 'dane': '15816'},
  {'name': 'Tópaga, Boyacá', 'dane': '15820'},
  {'name': 'Tota, Boyacá', 'dane': '15822'},
  {'name': 'Tununguá, Boyacá', 'dane': '15832'},
  {'name': 'Turmequé, Boyacá', 'dane': '15835'},
  {'name': 'Tuta, Boyacá', 'dane': '15837'},
  {'name': 'Tutazá, Boyacá', 'dane': '15839'},
  {'name': 'Úmbita, Boyacá', 'dane': '15842'},
  {'name': 'Ventaquemada, Boyacá', 'dane': '15861'},
  {'name': 'Viracachá, Boyacá', 'dane': '15879'},
  {'name': 'Zetaquira, Boyacá', 'dane': '15897'},
  {'name': 'Manizales, Caldas', 'dane': '17001'},
  {'name': 'Aguadas, Caldas', 'dane': '17013'},
  {'name': 'Anserma, Caldas', 'dane': '17042'},
  {'name': 'Aranzazu, Caldas', 'dane': '17050'},
  {'name': 'Belalcázar, Caldas', 'dane': '17088'},
  {'name': 'Chinchiná, Caldas', 'dane': '17174'},
  {'name': 'Filadelfia, Caldas', 'dane': '17272'},
  {'name': 'La Dorada, Caldas', 'dane': '17380'},
  {'name': 'La Merced, Caldas', 'dane': '17388'},
  {'name': 'Manzanares, Caldas', 'dane': '17433'},
  {'name': 'Marmato, Caldas', 'dane': '17442'},
  {'name': 'Marquetalia, Caldas', 'dane': '17444'},
  {'name': 'Marulanda, Caldas', 'dane': '17446'},
  {'name': 'Neira, Caldas', 'dane': '17486'},
  {'name': 'Norcasia, Caldas', 'dane': '17495'},
  {'name': 'Pácora, Caldas', 'dane': '17513'},
  {'name': 'Palestina, Caldas', 'dane': '17524'},
  {'name': 'Pensilvania, Caldas', 'dane': '17541'},
  {'name': 'Riosucio, Caldas', 'dane': '17614'},
  {'name': 'Risaralda, Caldas', 'dane': '17616'},
  {'name': 'Salamina, Caldas', 'dane': '17653'},
  {'name': 'Samaná, Caldas', 'dane': '17662'},
  {'name': 'San José, Caldas', 'dane': '17665'},
  {'name': 'Supía, Caldas', 'dane': '17777'},
  {'name': 'Victoria, Caldas', 'dane': '17867'},
  {'name': 'Villamaría, Caldas', 'dane': '17873'},
  {'name': 'Viterbo, Caldas', 'dane': '17877'},
  {'name': 'Florencia, Caquetá', 'dane': '18001'},
  {'name': 'Albania, Caquetá', 'dane': '18029'},
  {'name': 'Belén De Los Andaquíes, Caquetá', 'dane': '18094'},
  {'name': 'Cartagena Del Chairá, Caquetá', 'dane': '18150'},
  {'name': 'Curillo, Caquetá', 'dane': '18205'},
  {'name': 'El Doncello, Caquetá', 'dane': '18247'},
  {'name': 'El Paujíl, Caquetá', 'dane': '18256'},
  {'name': 'La Montañita, Caquetá', 'dane': '18410'},
  {'name': 'Milán, Caquetá', 'dane': '18460'},
  {'name': 'Morelia, Caquetá', 'dane': '18479'},
  {'name': 'Puerto Rico, Caquetá', 'dane': '18592'},
  {'name': 'San José Del Fragua, Caquetá', 'dane': '18610'},
  {'name': 'San Vicente Del Caguán, Caquetá', 'dane': '18753'},
  {'name': 'Solano, Caquetá', 'dane': '18756'},
  {'name': 'Solita, Caquetá', 'dane': '18785'},
  {'name': 'Valparaíso, Caquetá', 'dane': '18860'},
  {'name': 'Popayán, Cauca', 'dane': '19001'},
  {'name': 'Almaguer, Cauca', 'dane': '19022'},
  {'name': 'Argelia, Cauca', 'dane': '19050'},
  {'name': 'Balboa, Cauca', 'dane': '19075'},
  {'name': 'Bolívar, Cauca', 'dane': '19100'},
  {'name': 'Buenos Aires, Cauca', 'dane': '19110'},
  {'name': 'Cajibío, Cauca', 'dane': '19130'},
  {'name': 'Caldono, Cauca', 'dane': '19137'},
  {'name': 'Caloto, Cauca', 'dane': '19142'},
  {'name': 'Corinto, Cauca', 'dane': '19212'},
  {'name': 'El Tambo, Cauca', 'dane': '19256'},
  {'name': 'Florencia, Cauca', 'dane': '19290'},
  {'name': 'Guachené, Cauca', 'dane': '19300'},
  {'name': 'Guapi, Cauca', 'dane': '19318'},
  {'name': 'Inzá, Cauca', 'dane': '19355'},
  {'name': 'Jambaló, Cauca', 'dane': '19364'},
  {'name': 'La Sierra, Cauca', 'dane': '19392'},
  {'name': 'La Vega, Cauca', 'dane': '19397'},
  {'name': 'López De Micay, Cauca', 'dane': '19418'},
  {'name': 'Mercaderes, Cauca', 'dane': '19450'},
  {'name': 'Miranda, Cauca', 'dane': '19455'},
  {'name': 'Morales, Cauca', 'dane': '19473'},
  {'name': 'Padilla, Cauca', 'dane': '19513'},
  {'name': 'Páez, Cauca', 'dane': '19517'},
  {'name': 'Patía, Cauca', 'dane': '19532'},
  {'name': 'Piamonte, Cauca', 'dane': '19533'},
  {'name': 'Piendamó - Tunía, Cauca', 'dane': '19548'},
  {'name': 'Puerto Tejada, Cauca', 'dane': '19573'},
  {'name': 'Puracé, Cauca', 'dane': '19585'},
  {'name': 'Rosas, Cauca', 'dane': '19622'},
  {'name': 'San Sebastián, Cauca', 'dane': '19693'},
  {'name': 'Santander De Quilichao, Cauca', 'dane': '19698'},
  {'name': 'Santa Rosa, Cauca', 'dane': '19701'},
  {'name': 'Silvia, Cauca', 'dane': '19743'},
  {'name': 'Sotará - Paispamba, Cauca', 'dane': '19760'},
  {'name': 'Suárez, Cauca', 'dane': '19780'},
  {'name': 'Sucre, Cauca', 'dane': '19785'},
  {'name': 'Timbío, Cauca', 'dane': '19807'},
  {'name': 'Timbiquí, Cauca', 'dane': '19809'},
  {'name': 'Toribío, Cauca', 'dane': '19821'},
  {'name': 'Totoró, Cauca', 'dane': '19824'},
  {'name': 'Villa Rica, Cauca', 'dane': '19845'},
  {'name': 'Valledupar, Cesar', 'dane': '20001'},
  {'name': 'Aguachica, Cesar', 'dane': '20011'},
  {'name': 'Agustín Codazzi, Cesar', 'dane': '20013'},
  {'name': 'Astrea, Cesar', 'dane': '20032'},
  {'name': 'Becerril, Cesar', 'dane': '20045'},
  {'name': 'Bosconia, Cesar', 'dane': '20060'},
  {'name': 'Chimichagua, Cesar', 'dane': '20175'},
  {'name': 'Chiriguaná, Cesar', 'dane': '20178'},
  {'name': 'Curumaní, Cesar', 'dane': '20228'},
  {'name': 'El Copey, Cesar', 'dane': '20238'},
  {'name': 'El Paso, Cesar', 'dane': '20250'},
  {'name': 'Gamarra, Cesar', 'dane': '20295'},
  {'name': 'González, Cesar', 'dane': '20310'},
  {'name': 'La Gloria, Cesar', 'dane': '20383'},
  {'name': 'La Jagua De Ibirico, Cesar', 'dane': '20400'},
  {'name': 'Manaure Balcón Del Cesar, Cesar', 'dane': '20443'},
  {'name': 'Pailitas, Cesar', 'dane': '20517'},
  {'name': 'Pelaya, Cesar', 'dane': '20550'},
  {'name': 'Pueblo Bello, Cesar', 'dane': '20570'},
  {'name': 'Río De Oro, Cesar', 'dane': '20614'},
  {'name': 'La Paz, Cesar', 'dane': '20621'},
  {'name': 'San Alberto, Cesar', 'dane': '20710'},
  {'name': 'San Diego, Cesar', 'dane': '20750'},
  {'name': 'San Martín, Cesar', 'dane': '20770'},
  {'name': 'Tamalameque, Cesar', 'dane': '20787'},
  {'name': 'Montería, Córdoba', 'dane': '23001'},
  {'name': 'Ayapel, Córdoba', 'dane': '23068'},
  {'name': 'Buenavista, Córdoba', 'dane': '23079'},
  {'name': 'Canalete, Córdoba', 'dane': '23090'},
  {'name': 'Cereté, Córdoba', 'dane': '23162'},
  {'name': 'Chimá, Córdoba', 'dane': '23168'},
  {'name': 'Chinú, Córdoba', 'dane': '23182'},
  {'name': 'Ciénaga De Oro, Córdoba', 'dane': '23189'},
  {'name': 'Cotorra, Córdoba', 'dane': '23300'},
  {'name': 'La Apartada, Córdoba', 'dane': '23350'},
  {'name': 'Lorica, Córdoba', 'dane': '23417'},
  {'name': 'Los Córdobas, Córdoba', 'dane': '23419'},
  {'name': 'Momil, Córdoba', 'dane': '23464'},
  {'name': 'Montelíbano, Córdoba', 'dane': '23466'},
  {'name': 'Moñitos, Córdoba', 'dane': '23500'},
  {'name': 'Planeta Rica, Córdoba', 'dane': '23555'},
  {'name': 'Pueblo Nuevo, Córdoba', 'dane': '23570'},
  {'name': 'Puerto Escondido, Córdoba', 'dane': '23574'},
  {'name': 'Puerto Libertador, Córdoba', 'dane': '23580'},
  {'name': 'Purísima De La Concepción, Córdoba', 'dane': '23586'},
  {'name': 'Sahagún, Córdoba', 'dane': '23660'},
  {'name': 'San Andrés De Sotavento, Córdoba', 'dane': '23670'},
  {'name': 'San Antero, Córdoba', 'dane': '23672'},
  {'name': 'San Bernardo Del Viento, Córdoba', 'dane': '23675'},
  {'name': 'San Carlos, Córdoba', 'dane': '23678'},
  {'name': 'San José De Uré, Córdoba', 'dane': '23682'},
  {'name': 'San Pelayo, Córdoba', 'dane': '23686'},
  {'name': 'Tierralta, Córdoba', 'dane': '23807'},
  {'name': 'Tuchín, Córdoba', 'dane': '23815'},
  {'name': 'Valencia, Córdoba', 'dane': '23855'},
  {'name': 'Agua De Dios, Cundinamarca', 'dane': '25001'},
  {'name': 'Albán, Cundinamarca', 'dane': '25019'},
  {'name': 'Anapoima, Cundinamarca', 'dane': '25035'},
  {'name': 'Anolaima, Cundinamarca', 'dane': '25040'},
  {'name': 'Arbeláez, Cundinamarca', 'dane': '25053'},
  {'name': 'Beltrán, Cundinamarca', 'dane': '25086'},
  {'name': 'Bituima, Cundinamarca', 'dane': '25095'},
  {'name': 'Bojacá, Cundinamarca', 'dane': '25099'},
  {'name': 'Cabrera, Cundinamarca', 'dane': '25120'},
  {'name': 'Cachipay, Cundinamarca', 'dane': '25123'},
  {'name': 'Cajicá, Cundinamarca', 'dane': '25126'},
  {'name': 'Caparrapí, Cundinamarca', 'dane': '25148'},
  {'name': 'Cáqueza, Cundinamarca', 'dane': '25151'},
  {'name': 'Carmen De Carupa, Cundinamarca', 'dane': '25154'},
  {'name': 'Chaguaní, Cundinamarca', 'dane': '25168'},
  {'name': 'Chía, Cundinamarca', 'dane': '25175'},
  {'name': 'Chipaque, Cundinamarca', 'dane': '25178'},
  {'name': 'Choachí, Cundinamarca', 'dane': '25181'},
  {'name': 'Chocontá, Cundinamarca', 'dane': '25183'},
  {'name': 'Cogua, Cundinamarca', 'dane': '25200'},
  {'name': 'Cota, Cundinamarca', 'dane': '25214'},
  {'name': 'Cucunubá, Cundinamarca', 'dane': '25224'},
  {'name': 'El Colegio, Cundinamarca', 'dane': '25245'},
  {'name': 'El Peñón, Cundinamarca', 'dane': '25258'},
  {'name': 'El Rosal, Cundinamarca', 'dane': '25260'},
  {'name': 'Facatativá, Cundinamarca', 'dane': '25269'},
  {'name': 'Fómeque, Cundinamarca', 'dane': '25279'},
  {'name': 'Fosca, Cundinamarca', 'dane': '25281'},
  {'name': 'Funza, Cundinamarca', 'dane': '25286'},
  {'name': 'Fúquene, Cundinamarca', 'dane': '25288'},
  {'name': 'Fusagasugá, Cundinamarca', 'dane': '25290'},
  {'name': 'Gachalá, Cundinamarca', 'dane': '25293'},
  {'name': 'Gachancipá, Cundinamarca', 'dane': '25295'},
  {'name': 'Gachetá, Cundinamarca', 'dane': '25297'},
  {'name': 'Gama, Cundinamarca', 'dane': '25299'},
  {'name': 'Girardot, Cundinamarca', 'dane': '25307'},
  {'name': 'Granada, Cundinamarca', 'dane': '25312'},
  {'name': 'Guachetá, Cundinamarca', 'dane': '25317'},
  {'name': 'Guaduas, Cundinamarca', 'dane': '25320'},
  {'name': 'Guasca, Cundinamarca', 'dane': '25322'},
  {'name': 'Guataquí, Cundinamarca', 'dane': '25324'},
  {'name': 'Guatavita, Cundinamarca', 'dane': '25326'},
  {'name': 'Guayabal De Síquima, Cundinamarca', 'dane': '25328'},
  {'name': 'Guayabetal, Cundinamarca', 'dane': '25335'},
  {'name': 'Gutiérrez, Cundinamarca', 'dane': '25339'},
  {'name': 'Jerusalén, Cundinamarca', 'dane': '25368'},
  {'name': 'Junín, Cundinamarca', 'dane': '25372'},
  {'name': 'La Calera, Cundinamarca', 'dane': '25377'},
  {'name': 'La Mesa, Cundinamarca', 'dane': '25386'},
  {'name': 'La Palma, Cundinamarca', 'dane': '25394'},
  {'name': 'La Peña, Cundinamarca', 'dane': '25398'},
  {'name': 'La Vega, Cundinamarca', 'dane': '25402'},
  {'name': 'Lenguazaque, Cundinamarca', 'dane': '25407'},
  {'name': 'Machetá, Cundinamarca', 'dane': '25426'},
  {'name': 'Madrid, Cundinamarca', 'dane': '25430'},
  {'name': 'Manta, Cundinamarca', 'dane': '25436'},
  {'name': 'Medina, Cundinamarca', 'dane': '25438'},
  {'name': 'Mosquera, Cundinamarca', 'dane': '25473'},
  {'name': 'Nariño, Cundinamarca', 'dane': '25483'},
  {'name': 'Nemocón, Cundinamarca', 'dane': '25486'},
  {'name': 'Nilo, Cundinamarca', 'dane': '25488'},
  {'name': 'Nimaima, Cundinamarca', 'dane': '25489'},
  {'name': 'Nocaima, Cundinamarca', 'dane': '25491'},
  {'name': 'Venecia, Cundinamarca', 'dane': '25506'},
  {'name': 'Pacho, Cundinamarca', 'dane': '25513'},
  {'name': 'Paime, Cundinamarca', 'dane': '25518'},
  {'name': 'Pandi, Cundinamarca', 'dane': '25524'},
  {'name': 'Paratebueno, Cundinamarca', 'dane': '25530'},
  {'name': 'Pasca, Cundinamarca', 'dane': '25535'},
  {'name': 'Puerto Salgar, Cundinamarca', 'dane': '25572'},
  {'name': 'Pulí, Cundinamarca', 'dane': '25580'},
  {'name': 'Quebradanegra, Cundinamarca', 'dane': '25592'},
  {'name': 'Quetame, Cundinamarca', 'dane': '25594'},
  {'name': 'Quipile, Cundinamarca', 'dane': '25596'},
  {'name': 'Apulo, Cundinamarca', 'dane': '25599'},
  {'name': 'Ricaurte, Cundinamarca', 'dane': '25612'},
  {'name': 'San Antonio Del Tequendama, Cundinamarca', 'dane': '25645'},
  {'name': 'San Bernardo, Cundinamarca', 'dane': '25649'},
  {'name': 'San Cayetano, Cundinamarca', 'dane': '25653'},
  {'name': 'San Francisco, Cundinamarca', 'dane': '25658'},
  {'name': 'San Juan De Rioseco, Cundinamarca', 'dane': '25662'},
  {'name': 'Sasaima, Cundinamarca', 'dane': '25718'},
  {'name': 'Sesquilé, Cundinamarca', 'dane': '25736'},
  {'name': 'Sibaté, Cundinamarca', 'dane': '25740'},
  {'name': 'Silvania, Cundinamarca', 'dane': '25743'},
  {'name': 'Simijaca, Cundinamarca', 'dane': '25745'},
  {'name': 'Soacha, Cundinamarca', 'dane': '25754'},
  {'name': 'Sopó, Cundinamarca', 'dane': '25758'},
  {'name': 'Subachoque, Cundinamarca', 'dane': '25769'},
  {'name': 'Suesca, Cundinamarca', 'dane': '25772'},
  {'name': 'Supatá, Cundinamarca', 'dane': '25777'},
  {'name': 'Susa, Cundinamarca', 'dane': '25779'},
  {'name': 'Sutatausa, Cundinamarca', 'dane': '25781'},
  {'name': 'Tabio, Cundinamarca', 'dane': '25785'},
  {'name': 'Tausa, Cundinamarca', 'dane': '25793'},
  {'name': 'Tena, Cundinamarca', 'dane': '25797'},
  {'name': 'Tenjo, Cundinamarca', 'dane': '25799'},
  {'name': 'Tibacuy, Cundinamarca', 'dane': '25805'},
  {'name': 'Tibirita, Cundinamarca', 'dane': '25807'},
  {'name': 'Tocaima, Cundinamarca', 'dane': '25815'},
  {'name': 'Tocancipá, Cundinamarca', 'dane': '25817'},
  {'name': 'Topaipí, Cundinamarca', 'dane': '25823'},
  {'name': 'Ubalá, Cundinamarca', 'dane': '25839'},
  {'name': 'Ubaque, Cundinamarca', 'dane': '25841'},
  {'name': 'Villa De San Diego De Ubaté, Cundinamarca', 'dane': '25843'},
  {'name': 'Une, Cundinamarca', 'dane': '25845'},
  {'name': 'Útica, Cundinamarca', 'dane': '25851'},
  {'name': 'Vergara, Cundinamarca', 'dane': '25862'},
  {'name': 'Vianí, Cundinamarca', 'dane': '25867'},
  {'name': 'Villagómez, Cundinamarca', 'dane': '25871'},
  {'name': 'Villapinzón, Cundinamarca', 'dane': '25873'},
  {'name': 'Villeta, Cundinamarca', 'dane': '25875'},
  {'name': 'Viotá, Cundinamarca', 'dane': '25878'},
  {'name': 'Yacopí, Cundinamarca', 'dane': '25885'},
  {'name': 'Zipacón, Cundinamarca', 'dane': '25898'},
  {'name': 'Zipaquirá, Cundinamarca', 'dane': '25899'},
  {'name': 'Quibdó, Chocó', 'dane': '27001'},
  {'name': 'Acandí, Chocó', 'dane': '27006'},
  {'name': 'Alto Baudó, Chocó', 'dane': '27025'},
  {'name': 'Atrato, Chocó', 'dane': '27050'},
  {'name': 'Bagadó, Chocó', 'dane': '27073'},
  {'name': 'Bahía Solano, Chocó', 'dane': '27075'},
  {'name': 'Bajo Baudó, Chocó', 'dane': '27077'},
  {'name': 'Bojayá, Chocó', 'dane': '27099'},
  {'name': 'El Cantón Del San Pablo, Chocó', 'dane': '27135'},
  {'name': 'Carmen Del Darién, Chocó', 'dane': '27150'},
  {'name': 'Cértegui, Chocó', 'dane': '27160'},
  {'name': 'Condoto, Chocó', 'dane': '27205'},
  {'name': 'El Carmen De Atrato, Chocó', 'dane': '27245'},
  {'name': 'El Litoral Del San Juan, Chocó', 'dane': '27250'},
  {'name': 'Istmina, Chocó', 'dane': '27361'},
  {'name': 'Juradó, Chocó', 'dane': '27372'},
  {'name': 'Lloró, Chocó', 'dane': '27413'},
  {'name': 'Medio Atrato, Chocó', 'dane': '27425'},
  {'name': 'Medio Baudó, Chocó', 'dane': '27430'},
  {'name': 'Medio San Juan, Chocó', 'dane': '27450'},
  {'name': 'Nóvita, Chocó', 'dane': '27491'},
  {'name': 'Nuevo Belén De Bajirá, Chocó', 'dane': '27493'},
  {'name': 'Nuquí, Chocó', 'dane': '27495'},
  {'name': 'Río Iró, Chocó', 'dane': '27580'},
  {'name': 'Río Quito, Chocó', 'dane': '27600'},
  {'name': 'Riosucio, Chocó', 'dane': '27615'},
  {'name': 'San José Del Palmar, Chocó', 'dane': '27660'},
  {'name': 'Sipí, Chocó', 'dane': '27745'},
  {'name': 'Tadó, Chocó', 'dane': '27787'},
  {'name': 'Unguía, Chocó', 'dane': '27800'},
  {'name': 'Unión Panamericana, Chocó', 'dane': '27810'},
  {'name': 'Neiva, Huila', 'dane': '41001'},
  {'name': 'Acevedo, Huila', 'dane': '41006'},
  {'name': 'Agrado, Huila', 'dane': '41013'},
  {'name': 'Aipe, Huila', 'dane': '41016'},
  {'name': 'Algeciras, Huila', 'dane': '41020'},
  {'name': 'Altamira, Huila', 'dane': '41026'},
  {'name': 'Baraya, Huila', 'dane': '41078'},
  {'name': 'Campoalegre, Huila', 'dane': '41132'},
  {'name': 'Colombia, Huila', 'dane': '41206'},
  {'name': 'Elías, Huila', 'dane': '41244'},
  {'name': 'Garzón, Huila', 'dane': '41298'},
  {'name': 'Gigante, Huila', 'dane': '41306'},
  {'name': 'Guadalupe, Huila', 'dane': '41319'},
  {'name': 'Hobo, Huila', 'dane': '41349'},
  {'name': 'Íquira, Huila', 'dane': '41357'},
  {'name': 'Isnos, Huila', 'dane': '41359'},
  {'name': 'La Argentina, Huila', 'dane': '41378'},
  {'name': 'La Plata, Huila', 'dane': '41396'},
  {'name': 'Nátaga, Huila', 'dane': '41483'},
  {'name': 'Oporapa, Huila', 'dane': '41503'},
  {'name': 'Paicol, Huila', 'dane': '41518'},
  {'name': 'Palermo, Huila', 'dane': '41524'},
  {'name': 'Palestina, Huila', 'dane': '41530'},
  {'name': 'Pital, Huila', 'dane': '41548'},
  {'name': 'Pitalito, Huila', 'dane': '41551'},
  {'name': 'Rivera, Huila', 'dane': '41615'},
  {'name': 'Saladoblanco, Huila', 'dane': '41660'},
  {'name': 'San Agustín, Huila', 'dane': '41668'},
  {'name': 'Santa María, Huila', 'dane': '41676'},
  {'name': 'Suaza, Huila', 'dane': '41770'},
  {'name': 'Tarqui, Huila', 'dane': '41791'},
  {'name': 'Tesalia, Huila', 'dane': '41797'},
  {'name': 'Tello, Huila', 'dane': '41799'},
  {'name': 'Teruel, Huila', 'dane': '41801'},
  {'name': 'Timaná, Huila', 'dane': '41807'},
  {'name': 'Villavieja, Huila', 'dane': '41872'},
  {'name': 'Yaguará, Huila', 'dane': '41885'},
  {'name': 'Riohacha, La Guajira', 'dane': '44001'},
  {'name': 'Albania, La Guajira', 'dane': '44035'},
  {'name': 'Barrancas, La Guajira', 'dane': '44078'},
  {'name': 'Dibulla, La Guajira', 'dane': '44090'},
  {'name': 'Distracción, La Guajira', 'dane': '44098'},
  {'name': 'El Molino, La Guajira', 'dane': '44110'},
  {'name': 'Fonseca, La Guajira', 'dane': '44279'},
  {'name': 'Hatonuevo, La Guajira', 'dane': '44378'},
  {'name': 'La Jagua Del Pilar, La Guajira', 'dane': '44420'},
  {'name': 'Maicao, La Guajira', 'dane': '44430'},
  {'name': 'Manaure, La Guajira', 'dane': '44560'},
  {'name': 'San Juan Del Cesar, La Guajira', 'dane': '44650'},
  {'name': 'Uribia, La Guajira', 'dane': '44847'},
  {'name': 'Urumita, La Guajira', 'dane': '44855'},
  {'name': 'Villanueva, La Guajira', 'dane': '44874'},
  {'name': 'Santa Marta, Magdalena', 'dane': '47001'},
  {'name': 'Algarrobo, Magdalena', 'dane': '47030'},
  {'name': 'Aracataca, Magdalena', 'dane': '47053'},
  {'name': 'Ariguaní, Magdalena', 'dane': '47058'},
  {'name': 'Cerro De San Antonio, Magdalena', 'dane': '47161'},
  {'name': 'Chivolo, Magdalena', 'dane': '47170'},
  {'name': 'Ciénaga, Magdalena', 'dane': '47189'},
  {'name': 'Concordia, Magdalena', 'dane': '47205'},
  {'name': 'El Banco, Magdalena', 'dane': '47245'},
  {'name': 'El Piñón, Magdalena', 'dane': '47258'},
  {'name': 'El Retén, Magdalena', 'dane': '47268'},
  {'name': 'Fundación, Magdalena', 'dane': '47288'},
  {'name': 'Guamal, Magdalena', 'dane': '47318'},
  {'name': 'Nueva Granada, Magdalena', 'dane': '47460'},
  {'name': 'Pedraza, Magdalena', 'dane': '47541'},
  {'name': 'Pijiño Del Carmen, Magdalena', 'dane': '47545'},
  {'name': 'Pivijay, Magdalena', 'dane': '47551'},
  {'name': 'Plato, Magdalena', 'dane': '47555'},
  {'name': 'Puebloviejo, Magdalena', 'dane': '47570'},
  {'name': 'Remolino, Magdalena', 'dane': '47605'},
  {'name': 'Sabanas De San Ángel, Magdalena', 'dane': '47660'},
  {'name': 'Salamina, Magdalena', 'dane': '47675'},
  {'name': 'San Sebastián De Buenavista, Magdalena', 'dane': '47692'},
  {'name': 'San Zenón, Magdalena', 'dane': '47703'},
  {'name': 'Santa Ana, Magdalena', 'dane': '47707'},
  {'name': 'Santa Bárbara De Pinto, Magdalena', 'dane': '47720'},
  {'name': 'Sitionuevo, Magdalena', 'dane': '47745'},
  {'name': 'Tenerife, Magdalena', 'dane': '47798'},
  {'name': 'Zapayán, Magdalena', 'dane': '47960'},
  {'name': 'Zona Bananera, Magdalena', 'dane': '47980'},
  {'name': 'Villavicencio, Meta', 'dane': '50001'},
  {'name': 'Acacías, Meta', 'dane': '50006'},
  {'name': 'Barranca De Upía, Meta', 'dane': '50110'},
  {'name': 'Cabuyaro, Meta', 'dane': '50124'},
  {'name': 'Castilla La Nueva, Meta', 'dane': '50150'},
  {'name': 'Cubarral, Meta', 'dane': '50223'},
  {'name': 'Cumaral, Meta', 'dane': '50226'},
  {'name': 'El Calvario, Meta', 'dane': '50245'},
  {'name': 'El Castillo, Meta', 'dane': '50251'},
  {'name': 'El Dorado, Meta', 'dane': '50270'},
  {'name': 'Fuente De Oro, Meta', 'dane': '50287'},
  {'name': 'Granada, Meta', 'dane': '50313'},
  {'name': 'Guamal, Meta', 'dane': '50318'},
  {'name': 'Mapiripán, Meta', 'dane': '50325'},
  {'name': 'Mesetas, Meta', 'dane': '50330'},
  {'name': 'La Macarena, Meta', 'dane': '50350'},
  {'name': 'Uribe, Meta', 'dane': '50370'},
  {'name': 'Lejanías, Meta', 'dane': '50400'},
  {'name': 'Puerto Concordia, Meta', 'dane': '50450'},
  {'name': 'Puerto Gaitán, Meta', 'dane': '50568'},
  {'name': 'Puerto López, Meta', 'dane': '50573'},
  {'name': 'Puerto Lleras, Meta', 'dane': '50577'},
  {'name': 'Puerto Rico, Meta', 'dane': '50590'},
  {'name': 'Restrepo, Meta', 'dane': '50606'},
  {'name': 'San Carlos De Guaroa, Meta', 'dane': '50680'},
  {'name': 'San Juan De Arama, Meta', 'dane': '50683'},
  {'name': 'San Juanito, Meta', 'dane': '50686'},
  {'name': 'San Martín, Meta', 'dane': '50689'},
  {'name': 'Vistahermosa, Meta', 'dane': '50711'},
  {'name': 'Pasto, Nariño', 'dane': '52001'},
  {'name': 'Albán, Nariño', 'dane': '52019'},
  {'name': 'Aldana, Nariño', 'dane': '52022'},
  {'name': 'Ancuya, Nariño', 'dane': '52036'},
  {'name': 'Arboleda, Nariño', 'dane': '52051'},
  {'name': 'Barbacoas, Nariño', 'dane': '52079'},
  {'name': 'Belén, Nariño', 'dane': '52083'},
  {'name': 'Buesaco, Nariño', 'dane': '52110'},
  {'name': 'Colón, Nariño', 'dane': '52203'},
  {'name': 'Consacá, Nariño', 'dane': '52207'},
  {'name': 'Contadero, Nariño', 'dane': '52210'},
  {'name': 'Córdoba, Nariño', 'dane': '52215'},
  {'name': 'Cuaspud Carlosama, Nariño', 'dane': '52224'},
  {'name': 'Cumbal, Nariño', 'dane': '52227'},
  {'name': 'Cumbitara, Nariño', 'dane': '52233'},
  {'name': 'Chachagüí, Nariño', 'dane': '52240'},
  {'name': 'El Charco, Nariño', 'dane': '52250'},
  {'name': 'El Peñol, Nariño', 'dane': '52254'},
  {'name': 'El Rosario, Nariño', 'dane': '52256'},
  {'name': 'El Tablón De Gómez, Nariño', 'dane': '52258'},
  {'name': 'El Tambo, Nariño', 'dane': '52260'},
  {'name': 'Funes, Nariño', 'dane': '52287'},
  {'name': 'Guachucal, Nariño', 'dane': '52317'},
  {'name': 'Guaitarilla, Nariño', 'dane': '52320'},
  {'name': 'Gualmatán, Nariño', 'dane': '52323'},
  {'name': 'Iles, Nariño', 'dane': '52352'},
  {'name': 'Imués, Nariño', 'dane': '52354'},
  {'name': 'Ipiales, Nariño', 'dane': '52356'},
  {'name': 'La Cruz, Nariño', 'dane': '52378'},
  {'name': 'La Florida, Nariño', 'dane': '52381'},
  {'name': 'La Llanada, Nariño', 'dane': '52385'},
  {'name': 'La Tola, Nariño', 'dane': '52390'},
  {'name': 'La Unión, Nariño', 'dane': '52399'},
  {'name': 'Leiva, Nariño', 'dane': '52405'},
  {'name': 'Linares, Nariño', 'dane': '52411'},
  {'name': 'Los Andes, Nariño', 'dane': '52418'},
  {'name': 'Magüí, Nariño', 'dane': '52427'},
  {'name': 'Mallama, Nariño', 'dane': '52435'},
  {'name': 'Mosquera, Nariño', 'dane': '52473'},
  {'name': 'Nariño, Nariño', 'dane': '52480'},
  {'name': 'Olaya Herrera, Nariño', 'dane': '52490'},
  {'name': 'Ospina, Nariño', 'dane': '52506'},
  {'name': 'Francisco Pizarro, Nariño', 'dane': '52520'},
  {'name': 'Policarpa, Nariño', 'dane': '52540'},
  {'name': 'Potosí, Nariño', 'dane': '52560'},
  {'name': 'Providencia, Nariño', 'dane': '52565'},
  {'name': 'Puerres, Nariño', 'dane': '52573'},
  {'name': 'Pupiales, Nariño', 'dane': '52585'},
  {'name': 'Ricaurte, Nariño', 'dane': '52612'},
  {'name': 'Roberto Payán, Nariño', 'dane': '52621'},
  {'name': 'Samaniego, Nariño', 'dane': '52678'},
  {'name': 'Sandoná, Nariño', 'dane': '52683'},
  {'name': 'San Bernardo, Nariño', 'dane': '52685'},
  {'name': 'San Lorenzo, Nariño', 'dane': '52687'},
  {'name': 'San Pablo, Nariño', 'dane': '52693'},
  {'name': 'San Pedro De Cartago, Nariño', 'dane': '52694'},
  {'name': 'Santa Bárbara, Nariño', 'dane': '52696'},
  {'name': 'Santacruz, Nariño', 'dane': '52699'},
  {'name': 'Sapuyes, Nariño', 'dane': '52720'},
  {'name': 'Taminango, Nariño', 'dane': '52786'},
  {'name': 'Tangua, Nariño', 'dane': '52788'},
  {'name': 'San Andrés De Tumaco, Nariño', 'dane': '52835'},
  {'name': 'Túquerres, Nariño', 'dane': '52838'},
  {'name': 'Yacuanquer, Nariño', 'dane': '52885'},
  {'name': 'San José De Cúcuta, Norte De Santander', 'dane': '54001'},
  {'name': 'Ábrego, Norte De Santander', 'dane': '54003'},
  {'name': 'Arboledas, Norte De Santander', 'dane': '54051'},
  {'name': 'Bochalema, Norte De Santander', 'dane': '54099'},
  {'name': 'Bucarasica, Norte De Santander', 'dane': '54109'},
  {'name': 'Cácota, Norte De Santander', 'dane': '54125'},
  {'name': 'Cáchira, Norte De Santander', 'dane': '54128'},
  {'name': 'Chinácota, Norte De Santander', 'dane': '54172'},
  {'name': 'Chitagá, Norte De Santander', 'dane': '54174'},
  {'name': 'Convención, Norte De Santander', 'dane': '54206'},
  {'name': 'Cucutilla, Norte De Santander', 'dane': '54223'},
  {'name': 'Durania, Norte De Santander', 'dane': '54239'},
  {'name': 'El Carmen, Norte De Santander', 'dane': '54245'},
  {'name': 'El Tarra, Norte De Santander', 'dane': '54250'},
  {'name': 'El Zulia, Norte De Santander', 'dane': '54261'},
  {'name': 'Gramalote, Norte De Santander', 'dane': '54313'},
  {'name': 'Hacarí, Norte De Santander', 'dane': '54344'},
  {'name': 'Herrán, Norte De Santander', 'dane': '54347'},
  {'name': 'Labateca, Norte De Santander', 'dane': '54377'},
  {'name': 'La Esperanza, Norte De Santander', 'dane': '54385'},
  {'name': 'La Playa, Norte De Santander', 'dane': '54398'},
  {'name': 'Los Patios, Norte De Santander', 'dane': '54405'},
  {'name': 'Lourdes, Norte De Santander', 'dane': '54418'},
  {'name': 'Mutiscua, Norte De Santander', 'dane': '54480'},
  {'name': 'Ocaña, Norte De Santander', 'dane': '54498'},
  {'name': 'Pamplona, Norte De Santander', 'dane': '54518'},
  {'name': 'Pamplonita, Norte De Santander', 'dane': '54520'},
  {'name': 'Puerto Santander, Norte De Santander', 'dane': '54553'},
  {'name': 'Ragonvalia, Norte De Santander', 'dane': '54599'},
  {'name': 'Salazar, Norte De Santander', 'dane': '54660'},
  {'name': 'San Calixto, Norte De Santander', 'dane': '54670'},
  {'name': 'San Cayetano, Norte De Santander', 'dane': '54673'},
  {'name': 'Santiago, Norte De Santander', 'dane': '54680'},
  {'name': 'Sardinata, Norte De Santander', 'dane': '54720'},
  {'name': 'Silos, Norte De Santander', 'dane': '54743'},
  {'name': 'Teorama, Norte De Santander', 'dane': '54800'},
  {'name': 'Tibú, Norte De Santander', 'dane': '54810'},
  {'name': 'Toledo, Norte De Santander', 'dane': '54820'},
  {'name': 'Villa Caro, Norte De Santander', 'dane': '54871'},
  {'name': 'Villa Del Rosario, Norte De Santander', 'dane': '54874'},
  {'name': 'Armenia, Quindío', 'dane': '63001'},
  {'name': 'Buenavista, Quindío', 'dane': '63111'},
  {'name': 'Calarcá, Quindío', 'dane': '63130'},
  {'name': 'Circasia, Quindío', 'dane': '63190'},
  {'name': 'Córdoba, Quindío', 'dane': '63212'},
  {'name': 'Filandia, Quindío', 'dane': '63272'},
  {'name': 'Génova, Quindío', 'dane': '63302'},
  {'name': 'La Tebaida, Quindío', 'dane': '63401'},
  {'name': 'Montenegro, Quindío', 'dane': '63470'},
  {'name': 'Pijao, Quindío', 'dane': '63548'},
  {'name': 'Quimbaya, Quindío', 'dane': '63594'},
  {'name': 'Salento, Quindío', 'dane': '63690'},
  {'name': 'Pereira, Risaralda', 'dane': '66001'},
  {'name': 'Apía, Risaralda', 'dane': '66045'},
  {'name': 'Balboa, Risaralda', 'dane': '66075'},
  {'name': 'Belén De Umbría, Risaralda', 'dane': '66088'},
  {'name': 'Dosquebradas, Risaralda', 'dane': '66170'},
  {'name': 'Guática, Risaralda', 'dane': '66318'},
  {'name': 'La Celia, Risaralda', 'dane': '66383'},
  {'name': 'La Virginia, Risaralda', 'dane': '66400'},
  {'name': 'Marsella, Risaralda', 'dane': '66440'},
  {'name': 'Mistrató, Risaralda', 'dane': '66456'},
  {'name': 'Pueblo Rico, Risaralda', 'dane': '66572'},
  {'name': 'Quinchía, Risaralda', 'dane': '66594'},
  {'name': 'Santa Rosa De Cabal, Risaralda', 'dane': '66682'},
  {'name': 'Santuario, Risaralda', 'dane': '66687'},
  {'name': 'Bucaramanga, Santander', 'dane': '68001'},
  {'name': 'Aguada, Santander', 'dane': '68013'},
  {'name': 'Albania, Santander', 'dane': '68020'},
  {'name': 'Aratoca, Santander', 'dane': '68051'},
  {'name': 'Barbosa, Santander', 'dane': '68077'},
  {'name': 'Barichara, Santander', 'dane': '68079'},
  {'name': 'Barrancabermeja, Santander', 'dane': '68081'},
  {'name': 'Betulia, Santander', 'dane': '68092'},
  {'name': 'Bolívar, Santander', 'dane': '68101'},
  {'name': 'Cabrera, Santander', 'dane': '68121'},
  {'name': 'California, Santander', 'dane': '68132'},
  {'name': 'Capitanejo, Santander', 'dane': '68147'},
  {'name': 'Carcasí, Santander', 'dane': '68152'},
  {'name': 'Cepitá, Santander', 'dane': '68160'},
  {'name': 'Cerrito, Santander', 'dane': '68162'},
  {'name': 'Charalá, Santander', 'dane': '68167'},
  {'name': 'Charta, Santander', 'dane': '68169'},
  {'name': 'Chima, Santander', 'dane': '68176'},
  {'name': 'Chipatá, Santander', 'dane': '68179'},
  {'name': 'Cimitarra, Santander', 'dane': '68190'},
  {'name': 'Concepción, Santander', 'dane': '68207'},
  {'name': 'Confines, Santander', 'dane': '68209'},
  {'name': 'Contratación, Santander', 'dane': '68211'},
  {'name': 'Coromoro, Santander', 'dane': '68217'},
  {'name': 'Curití, Santander', 'dane': '68229'},
  {'name': 'El Carmen De Chucurí, Santander', 'dane': '68235'},
  {'name': 'El Guacamayo, Santander', 'dane': '68245'},
  {'name': 'El Peñón, Santander', 'dane': '68250'},
  {'name': 'El Playón, Santander', 'dane': '68255'},
  {'name': 'Encino, Santander', 'dane': '68264'},
  {'name': 'Enciso, Santander', 'dane': '68266'},
  {'name': 'Florián, Santander', 'dane': '68271'},
  {'name': 'Floridablanca, Santander', 'dane': '68276'},
  {'name': 'Galán, Santander', 'dane': '68296'},
  {'name': 'Gámbita, Santander', 'dane': '68298'},
  {'name': 'Girón, Santander', 'dane': '68307'},
  {'name': 'Guaca, Santander', 'dane': '68318'},
  {'name': 'Guadalupe, Santander', 'dane': '68320'},
  {'name': 'Guapotá, Santander', 'dane': '68322'},
  {'name': 'Guavatá, Santander', 'dane': '68324'},
  {'name': 'Güepsa, Santander', 'dane': '68327'},
  {'name': 'Hato, Santander', 'dane': '68344'},
  {'name': 'Jesús María, Santander', 'dane': '68368'},
  {'name': 'Jordán, Santander', 'dane': '68370'},
  {'name': 'La Belleza, Santander', 'dane': '68377'},
  {'name': 'Landázuri, Santander', 'dane': '68385'},
  {'name': 'La Paz, Santander', 'dane': '68397'},
  {'name': 'Lebrija, Santander', 'dane': '68406'},
  {'name': 'Los Santos, Santander', 'dane': '68418'},
  {'name': 'Macaravita, Santander', 'dane': '68425'},
  {'name': 'Málaga, Santander', 'dane': '68432'},
  {'name': 'Matanza, Santander', 'dane': '68444'},
  {'name': 'Mogotes, Santander', 'dane': '68464'},
  {'name': 'Molagavita, Santander', 'dane': '68468'},
  {'name': 'Ocamonte, Santander', 'dane': '68498'},
  {'name': 'Oiba, Santander', 'dane': '68500'},
  {'name': 'Onzaga, Santander', 'dane': '68502'},
  {'name': 'Palmar, Santander', 'dane': '68522'},
  {'name': 'Palmas Del Socorro, Santander', 'dane': '68524'},
  {'name': 'Páramo, Santander', 'dane': '68533'},
  {'name': 'Piedecuesta, Santander', 'dane': '68547'},
  {'name': 'Pinchote, Santander', 'dane': '68549'},
  {'name': 'Puente Nacional, Santander', 'dane': '68572'},
  {'name': 'Puerto Parra, Santander', 'dane': '68573'},
  {'name': 'Puerto Wilches, Santander', 'dane': '68575'},
  {'name': 'Rionegro, Santander', 'dane': '68615'},
  {'name': 'Sabana De Torres, Santander', 'dane': '68655'},
  {'name': 'San Andrés, Santander', 'dane': '68669'},
  {'name': 'San Benito, Santander', 'dane': '68673'},
  {'name': 'San Gil, Santander', 'dane': '68679'},
  {'name': 'San Joaquín, Santander', 'dane': '68682'},
  {'name': 'San José De Miranda, Santander', 'dane': '68684'},
  {'name': 'San Miguel, Santander', 'dane': '68686'},
  {'name': 'San Vicente De Chucurí, Santander', 'dane': '68689'},
  {'name': 'Santa Bárbara, Santander', 'dane': '68705'},
  {'name': 'Santa Helena Del Opón, Santander', 'dane': '68720'},
  {'name': 'Simacota, Santander', 'dane': '68745'},
  {'name': 'Socorro, Santander', 'dane': '68755'},
  {'name': 'Suaita, Santander', 'dane': '68770'},
  {'name': 'Sucre, Santander', 'dane': '68773'},
  {'name': 'Suratá, Santander', 'dane': '68780'},
  {'name': 'Tona, Santander', 'dane': '68820'},
  {'name': 'Valle De San José, Santander', 'dane': '68855'},
  {'name': 'Vélez, Santander', 'dane': '68861'},
  {'name': 'Vetas, Santander', 'dane': '68867'},
  {'name': 'Villanueva, Santander', 'dane': '68872'},
  {'name': 'Zapatoca, Santander', 'dane': '68895'},
  {'name': 'Sincelejo, Sucre', 'dane': '70001'},
  {'name': 'Buenavista, Sucre', 'dane': '70110'},
  {'name': 'Caimito, Sucre', 'dane': '70124'},
  {'name': 'Colosó, Sucre', 'dane': '70204'},
  {'name': 'Corozal, Sucre', 'dane': '70215'},
  {'name': 'Coveñas, Sucre', 'dane': '70221'},
  {'name': 'Chalán, Sucre', 'dane': '70230'},
  {'name': 'El Roble, Sucre', 'dane': '70233'},
  {'name': 'Galeras, Sucre', 'dane': '70235'},
  {'name': 'Guaranda, Sucre', 'dane': '70265'},
  {'name': 'La Unión, Sucre', 'dane': '70400'},
  {'name': 'Los Palmitos, Sucre', 'dane': '70418'},
  {'name': 'Majagual, Sucre', 'dane': '70429'},
  {'name': 'Morroa, Sucre', 'dane': '70473'},
  {'name': 'Ovejas, Sucre', 'dane': '70508'},
  {'name': 'Palmito, Sucre', 'dane': '70523'},
  {'name': 'Sampués, Sucre', 'dane': '70670'},
  {'name': 'San Benito Abad, Sucre', 'dane': '70678'},
  {'name': 'San Juan De Betulia, Sucre', 'dane': '70702'},
  {'name': 'San Marcos, Sucre', 'dane': '70708'},
  {'name': 'San Onofre, Sucre', 'dane': '70713'},
  {'name': 'San Pedro, Sucre', 'dane': '70717'},
  {'name': 'San Luis De Sincé, Sucre', 'dane': '70742'},
  {'name': 'Sucre, Sucre', 'dane': '70771'},
  {'name': 'Santiago De Tolú, Sucre', 'dane': '70820'},
  {'name': 'San José De Toluviejo, Sucre', 'dane': '70823'},
  {'name': 'Ibagué, Tolima', 'dane': '73001'},
  {'name': 'Alpujarra, Tolima', 'dane': '73024'},
  {'name': 'Alvarado, Tolima', 'dane': '73026'},
  {'name': 'Ambalema, Tolima', 'dane': '73030'},
  {'name': 'Anzoátegui, Tolima', 'dane': '73043'},
  {'name': 'Armero, Tolima', 'dane': '73055'},
  {'name': 'Ataco, Tolima', 'dane': '73067'},
  {'name': 'Cajamarca, Tolima', 'dane': '73124'},
  {'name': 'Carmen De Apicalá, Tolima', 'dane': '73148'},
  {'name': 'Casabianca, Tolima', 'dane': '73152'},
  {'name': 'Chaparral, Tolima', 'dane': '73168'},
  {'name': 'Coello, Tolima', 'dane': '73200'},
  {'name': 'Coyaima, Tolima', 'dane': '73217'},
  {'name': 'Cunday, Tolima', 'dane': '73226'},
  {'name': 'Dolores, Tolima', 'dane': '73236'},
  {'name': 'Espinal, Tolima', 'dane': '73268'},
  {'name': 'Falan, Tolima', 'dane': '73270'},
  {'name': 'Flandes, Tolima', 'dane': '73275'},
  {'name': 'Fresno, Tolima', 'dane': '73283'},
  {'name': 'Guamo, Tolima', 'dane': '73319'},
  {'name': 'Herveo, Tolima', 'dane': '73347'},
  {'name': 'Honda, Tolima', 'dane': '73349'},
  {'name': 'Icononzo, Tolima', 'dane': '73352'},
  {'name': 'Lérida, Tolima', 'dane': '73408'},
  {'name': 'Líbano, Tolima', 'dane': '73411'},
  {'name': 'San Sebastián De Mariquita, Tolima', 'dane': '73443'},
  {'name': 'Melgar, Tolima', 'dane': '73449'},
  {'name': 'Murillo, Tolima', 'dane': '73461'},
  {'name': 'Natagaima, Tolima', 'dane': '73483'},
  {'name': 'Ortega, Tolima', 'dane': '73504'},
  {'name': 'Palocabildo, Tolima', 'dane': '73520'},
  {'name': 'Piedras, Tolima', 'dane': '73547'},
  {'name': 'Planadas, Tolima', 'dane': '73555'},
  {'name': 'Prado, Tolima', 'dane': '73563'},
  {'name': 'Purificación, Tolima', 'dane': '73585'},
  {'name': 'Rioblanco, Tolima', 'dane': '73616'},
  {'name': 'Roncesvalles, Tolima', 'dane': '73622'},
  {'name': 'Rovira, Tolima', 'dane': '73624'},
  {'name': 'Saldaña, Tolima', 'dane': '73671'},
  {'name': 'San Antonio, Tolima', 'dane': '73675'},
  {'name': 'San Luis, Tolima', 'dane': '73678'},
  {'name': 'Santa Isabel, Tolima', 'dane': '73686'},
  {'name': 'Suárez, Tolima', 'dane': '73770'},
  {'name': 'Valle De San Juan, Tolima', 'dane': '73854'},
  {'name': 'Venadillo, Tolima', 'dane': '73861'},
  {'name': 'Villahermosa, Tolima', 'dane': '73870'},
  {'name': 'Villarrica, Tolima', 'dane': '73873'},
  {'name': 'Santiago De Cali, Valle Del Cauca', 'dane': '76001'},
  {'name': 'Alcalá, Valle Del Cauca', 'dane': '76020'},
  {'name': 'Andalucía, Valle Del Cauca', 'dane': '76036'},
  {'name': 'Ansermanuevo, Valle Del Cauca', 'dane': '76041'},
  {'name': 'Argelia, Valle Del Cauca', 'dane': '76054'},
  {'name': 'Bolívar, Valle Del Cauca', 'dane': '76100'},
  {'name': 'Buenaventura, Valle Del Cauca', 'dane': '76109'},
  {'name': 'Guadalajara De Buga, Valle Del Cauca', 'dane': '76111'},
  {'name': 'Bugalagrande, Valle Del Cauca', 'dane': '76113'},
  {'name': 'Caicedonia, Valle Del Cauca', 'dane': '76122'},
  {'name': 'Calima, Valle Del Cauca', 'dane': '76126'},
  {'name': 'Candelaria, Valle Del Cauca', 'dane': '76130'},
  {'name': 'Cartago, Valle Del Cauca', 'dane': '76147'},
  {'name': 'Dagua, Valle Del Cauca', 'dane': '76233'},
  {'name': 'El Águila, Valle Del Cauca', 'dane': '76243'},
  {'name': 'El Cairo, Valle Del Cauca', 'dane': '76246'},
  {'name': 'El Cerrito, Valle Del Cauca', 'dane': '76248'},
  {'name': 'El Dovio, Valle Del Cauca', 'dane': '76250'},
  {'name': 'Florida, Valle Del Cauca', 'dane': '76275'},
  {'name': 'Ginebra, Valle Del Cauca', 'dane': '76306'},
  {'name': 'Guacarí, Valle Del Cauca', 'dane': '76318'},
  {'name': 'Jamundí, Valle Del Cauca', 'dane': '76364'},
  {'name': 'La Cumbre, Valle Del Cauca', 'dane': '76377'},
  {'name': 'La Unión, Valle Del Cauca', 'dane': '76400'},
  {'name': 'La Victoria, Valle Del Cauca', 'dane': '76403'},
  {'name': 'Obando, Valle Del Cauca', 'dane': '76497'},
  {'name': 'Palmira, Valle Del Cauca', 'dane': '76520'},
  {'name': 'Pradera, Valle Del Cauca', 'dane': '76563'},
  {'name': 'Restrepo, Valle Del Cauca', 'dane': '76606'},
  {'name': 'Riofrío, Valle Del Cauca', 'dane': '76616'},
  {'name': 'Roldanillo, Valle Del Cauca', 'dane': '76622'},
  {'name': 'San Pedro, Valle Del Cauca', 'dane': '76670'},
  {'name': 'Sevilla, Valle Del Cauca', 'dane': '76736'},
  {'name': 'Toro, Valle Del Cauca', 'dane': '76823'},
  {'name': 'Trujillo, Valle Del Cauca', 'dane': '76828'},
  {'name': 'Tuluá, Valle Del Cauca', 'dane': '76834'},
  {'name': 'Ulloa, Valle Del Cauca', 'dane': '76845'},
  {'name': 'Versalles, Valle Del Cauca', 'dane': '76863'},
  {'name': 'Vijes, Valle Del Cauca', 'dane': '76869'},
  {'name': 'Yotoco, Valle Del Cauca', 'dane': '76890'},
  {'name': 'Yumbo, Valle Del Cauca', 'dane': '76892'},
  {'name': 'Zarzal, Valle Del Cauca', 'dane': '76895'},
  {'name': 'Arauca, Arauca', 'dane': '81001'},
  {'name': 'Arauquita, Arauca', 'dane': '81065'},
  {'name': 'Cravo Norte, Arauca', 'dane': '81220'},
  {'name': 'Fortul, Arauca', 'dane': '81300'},
  {'name': 'Puerto Rondón, Arauca', 'dane': '81591'},
  {'name': 'Saravena, Arauca', 'dane': '81736'},
  {'name': 'Tame, Arauca', 'dane': '81794'},
  {'name': 'Yopal, Casanare', 'dane': '85001'},
  {'name': 'Aguazul, Casanare', 'dane': '85010'},
  {'name': 'Chámeza, Casanare', 'dane': '85015'},
  {'name': 'Hato Corozal, Casanare', 'dane': '85125'},
  {'name': 'La Salina, Casanare', 'dane': '85136'},
  {'name': 'Maní, Casanare', 'dane': '85139'},
  {'name': 'Monterrey, Casanare', 'dane': '85162'},
  {'name': 'Nunchía, Casanare', 'dane': '85225'},
  {'name': 'Orocué, Casanare', 'dane': '85230'},
  {'name': 'Paz De Ariporo, Casanare', 'dane': '85250'},
  {'name': 'Pore, Casanare', 'dane': '85263'},
  {'name': 'Recetor, Casanare', 'dane': '85279'},
  {'name': 'Sabanalarga, Casanare', 'dane': '85300'},
  {'name': 'Sácama, Casanare', 'dane': '85315'},
  {'name': 'San Luis De Palenque, Casanare', 'dane': '85325'},
  {'name': 'Támara, Casanare', 'dane': '85400'},
  {'name': 'Tauramena, Casanare', 'dane': '85410'},
  {'name': 'Trinidad, Casanare', 'dane': '85430'},
  {'name': 'Villanueva, Casanare', 'dane': '85440'},
  {'name': 'Mocoa, Putumayo', 'dane': '86001'},
  {'name': 'Colón, Putumayo', 'dane': '86219'},
  {'name': 'Orito, Putumayo', 'dane': '86320'},
  {'name': 'Puerto Asís, Putumayo', 'dane': '86568'},
  {'name': 'Puerto Caicedo, Putumayo', 'dane': '86569'},
  {'name': 'Puerto Guzmán, Putumayo', 'dane': '86571'},
  {'name': 'Puerto Leguízamo, Putumayo', 'dane': '86573'},
  {'name': 'Sibundoy, Putumayo', 'dane': '86749'},
  {'name': 'San Francisco, Putumayo', 'dane': '86755'},
  {'name': 'San Miguel, Putumayo', 'dane': '86757'},
  {'name': 'Santiago, Putumayo', 'dane': '86760'},
  {'name': 'Valle Del Guamuez, Putumayo', 'dane': '86865'},
  {'name': 'Villagarzón, Putumayo', 'dane': '86885'},
  {'name': 'San Andrés, Archipiélago De San Andrés, Providencia Y Santa Catalina', 'dane': '88001'},
  {'name': 'Providencia, Archipiélago De San Andrés, Providencia Y Santa Catalina', 'dane': '88564'},
  {'name': 'Leticia, Amazonas', 'dane': '91001'},
  {'name': 'El Encanto, Amazonas', 'dane': '91263'},
  {'name': 'La Chorrera, Amazonas', 'dane': '91405'},
  {'name': 'La Pedrera, Amazonas', 'dane': '91407'},
  {'name': 'La Victoria, Amazonas', 'dane': '91430'},
  {'name': 'Mirití - Paraná, Amazonas', 'dane': '91460'},
  {'name': 'Puerto Alegría, Amazonas', 'dane': '91530'},
  {'name': 'Puerto Arica, Amazonas', 'dane': '91536'},
  {'name': 'Puerto Nariño, Amazonas', 'dane': '91540'},
  {'name': 'Puerto Santander, Amazonas', 'dane': '91669'},
  {'name': 'Tarapacá, Amazonas', 'dane': '91798'},
  {'name': 'Inírida, Guainía', 'dane': '94001'},
  {'name': 'Barrancominas, Guainía', 'dane': '94343'},
  {'name': 'San Felipe, Guainía', 'dane': '94883'},
  {'name': 'Puerto Colombia, Guainía', 'dane': '94884'},
  {'name': 'La Guadalupe, Guainía', 'dane': '94885'},
  {'name': 'Cacahual, Guainía', 'dane': '94886'},
  {'name': 'Pana Pana, Guainía', 'dane': '94887'},
  {'name': 'Morichal, Guainía', 'dane': '94888'},
  {'name': 'San José Del Guaviare, Guaviare', 'dane': '95001'},
  {'name': 'Calamar, Guaviare', 'dane': '95015'},
  {'name': 'El Retorno, Guaviare', 'dane': '95025'},
  {'name': 'Miraflores, Guaviare', 'dane': '95200'},
  {'name': 'Mitú, Vaupés', 'dane': '97001'},
  {'name': 'Carurú, Vaupés', 'dane': '97161'},
  {'name': 'Pacoa, Vaupés', 'dane': '97511'},
  {'name': 'Taraira, Vaupés', 'dane': '97666'},
  {'name': 'Papunahua, Vaupés', 'dane': '97777'},
  {'name': 'Yavaraté, Vaupés', 'dane': '97889'},
  {'name': 'Puerto Carreño, Vichada', 'dane': '99001'},
  {'name': 'La Primavera, Vichada', 'dane': '99524'},
  {'name': 'Santa Rosalía, Vichada', 'dane': '99624'},
  {'name': 'Cumaribo, Vichada', 'dane': '99773'},
];
