// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtC9CZkDREkReMYdAqXYHpsVKZjQWK0gw',
    appId: '1:520665025106:web:cce147ea179be3e68b2d8b',
    messagingSenderId: '520665025106',
    projectId: 'konta-dev-49cb7',
    authDomain: 'konta-dev-49cb7.firebaseapp.com',
    storageBucket: 'konta-dev-49cb7.firebasestorage.app',
    measurementId: 'G-T9P3NZMSEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzZhQL-eDWWmJMsYK5NLM_Z8PoRq38rJk',
    appId: '1:520665025106:android:ab5d2210e41ebe338b2d8b',
    messagingSenderId: '520665025106',
    projectId: 'konta-dev-49cb7',
    storageBucket: 'konta-dev-49cb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoooJHPUWX0yltUk_ndJfbO_WLKPe87ls',
    appId: '1:520665025106:ios:9e5ddb61f6c145f48b2d8b',
    messagingSenderId: '520665025106',
    projectId: 'konta-dev-49cb7',
    storageBucket: 'konta-dev-49cb7.firebasestorage.app',
    iosBundleId: 'com.example.kontaGestor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoooJHPUWX0yltUk_ndJfbO_WLKPe87ls',
    appId: '1:520665025106:ios:9e5ddb61f6c145f48b2d8b',
    messagingSenderId: '520665025106',
    projectId: 'konta-dev-49cb7',
    storageBucket: 'konta-dev-49cb7.firebasestorage.app',
    iosBundleId: 'com.example.kontaGestor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdHj4iKyHjlKxBVqtUNz7qu-0W_qhh4nQ',
    appId: '1:520665025106:web:7842fd6f7dff94698b2d8b',
    messagingSenderId: '520665025106',
    projectId: 'konta-dev-49cb7',
    authDomain: 'konta-dev-49cb7.firebaseapp.com',
    storageBucket: 'konta-dev-49cb7.firebasestorage.app',
    measurementId: 'G-13JDSZ9JH2',
  );

}